function test_find_initial_t_stability()
%TEST_FIND_INITIAL_T_STABILITY 验证 FindInitialT 对退化对角线的稳健性。
%   该测试覆盖零对角元素和带有负对角元素的示例，确保生成的
%   初始参数向量中不存在 NaN 或 Inf。

    test_cases = {
        struct( ...
            'name', 'zero diagonal entries', ...
            'rho', [0, 0.1 + 0.2i, 0; 0.1 - 0.2i, 0, 0.05; 0, 0.05, 1], ...
            'dimension', 3), ...
        struct( ...
            'name', 'negative diagonal entry', ...
            'rho', [-1e-3, 0.2; 0.2, 1.001], ...
            'dimension', 2) ...
    };

    for k = 1:numel(test_cases)
        case_info = test_cases{k};
        initial_vector = FindInitialT(case_info.rho, case_info.dimension);
        assert(all(isfinite(initial_vector)), ...
            'FindInitialT produced non-finite values for case "%s".', ...
            case_info.name);
    end

    disp('FindInitialT stability tests passed.');
end
